-- 코드를 입력하세요
WITH CC AS (
    SELECT CART_ID, GROUP_CONCAT(NAME SEPARATOR ', ') AS NAMES
    FROM CART_PRODUCTS
    GROUP BY CART_ID
)

SELECT CART_ID
FROM CC
WHERE NAMES LIKE '%Milk%' AND NAMES LIKE '%Yogurt%'
ORDER BY CART_ID ASC