SELECT P.PRODUCT_CODE, COALESCE(SUM(P.PRICE * O.SALES_AMOUNT), 0) AS SALES
FROM PRODUCT P
LEFT JOIN OFFLINE_SALE O ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE ASC