-- 코드를 입력하세요
WITH AVAILCARS AS (
    SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON C.CAR_ID = H.CAR_ID
    AND H.START_DATE <= '2022-11-30' AND H.END_DATE >= '2022-11-01'
    WHERE H.CAR_ID IS NULL
    AND (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV')
),
DISCOUNTED AS (
    SELECT AC.CAR_ID, AC.CAR_TYPE, AC.DAILY_FEE, D.DISCOUNT_RATE
    FROM AVAILCARS AC
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
    ON AC.CAR_TYPE = D.CAR_TYPE
    WHERE D.DURATION_TYPE = '30일 이상'
)
SELECT DC.CAR_ID, DC.CAR_TYPE,
       FLOOR(DC.DAILY_FEE * (1 - DC.DISCOUNT_RATE / 100) * 30) AS FEE
FROM DISCOUNTED DC
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, DC.CAR_TYPE ASC, DC.CAR_ID DESC;
